# Specify the python runtime
runtime: python37

# Specify the python version
# runtime_config:
#   python_version: 3.7

# Specify the entrypoint command to run the fastapi app with gunicorn
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

# Specify the handlers for different URL patterns
handlers:
- url: /.*
  script: auto

# Specify the resources for your app, such as memory, cpu, disk, etc.
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
